export const ListOfOrchids = [
  {
    id: 1,
    name: "Taichung beauty",
    rating: 5,
    isSpecial: true,
    image: "https://barritaorchids.com/cdn/shop/products/Cf592_1024x1024.jpg",
    color: "pink",
    origin: "Taiwan",
    category: "Dendrobium",
  },
  {
    id: 2,
    name: "Vivian Rose",
    rating: 4.5,
    isSpecial: false,
    image:
      "https://cdn05.zipify.com/d3d3YkdVxc7IAIooQFahf7EY_p8=/0x0:3000x3000/fit-in/1080x0/f1f3dbb2480e496e84cbe767fae64eaf/orchid-centerpiece-arrangement-faux-orchid-arrangement.png",
    color: "white",
    origin: "USA",
    category: "Cattleya",
  },
  {
    id: 3,
    name: "Lan Ngọc Điểm",
    rating: 3.5,
    isSpecial: true,
    image: "http://hoanglanorchids.vn/upload/sanpham/m-0156-56.jpg",
    color: "pink",
    origin: "Taiwan",
    category: "Cymbidium",
  },
  {
    id: 4,
    name: "Lan Hạc vỹ",
    rating: 4,
    isSpecial: true,
    image: "http://hoanglanorchids.vn/upload/sanpham/ms-2122.jpg",
    color: "pink",
    origin: "Taiwan",
    category: "Catasetum",
  },
  {
    id: 5,
    name: "Lan Dendro",
    rating: 5,
    isSpecial: false,
    image:
      "http://hoanglanorchids.vn/upload/user/images/y-nghia-hoa-lan-cach-cham-soc-hoa-lan-tinmoi-1.jpg",
    color: "white",
    origin: "Taiwan",
    category: "Dendrobium",
  },
  {
    id: 6,
    name: "Lan Long tu Lào",
    rating: 4.5,
    isSpecial: false,
    image:
      "https://cdn05.zipify.com/8ur9oa6m8oIdaAbcOla5t07fuhw=/0x0:2024x2024/fit-in/1080x0/174ed1dae2b942c3948d181c7a10aef4/large-faux-pink-orchid-arrangement-in-glass-vase-centerpiece-faux-floral-luxury-artificial-flowers-silk-vivian-rose_1024x1024-2x.jpeg",
    color: "pink",
    origin: "Taiwan",
    category: "Miniature",
  },
  {
    id: 7,
    name: "Lan Long tu Lào",
    rating: 5,
    isSpecial: true,
    image:
      "https://cdn05.zipify.com/8ur9oa6m8oIdaAbcOla5t07fuhw=/0x0:2024x2024/fit-in/1080x0/174ed1dae2b942c3948d181c7a10aef4/large-faux-pink-orchid-arrangement-in-glass-vase-centerpiece-faux-floral-luxury-artificial-flowers-silk-vivian-rose_1024x1024-2x.jpeg",
    color: "pink",
    origin: "Taiwan",
    category: "Cattleya",
  },
  {
    id: 8,
    name: "Chậu Lan Hồ Điệp Hồng Phát",
    rating: 4.5,
    isSpecial: false,
    image:
      "https://hoaviet247.com/wp-content/uploads/2024/03/lan-ho-diep-cl010-chau-lan-dep.jpg",
    color: "pink",
    origin: "Taiwan",
    category: "Dendrobium",
  },
  {
    id: 9,
    name: "Lan Long tu Lào",
    rating: 5,
    isSpecial: false,
    image:
      "https://cdn05.zipify.com/8ur9oa6m8oIdaAbcOla5t07fuhw=/0x0:2024x2024/fit-in/1080x0/174ed1dae2b942c3948d181c7a10aef4/large-faux-pink-orchid-arrangement-in-glass-vase-centerpiece-faux-floral-luxury-artificial-flowers-silk-vivian-rose_1024x1024-2x.jpeg",
    color: "pink",
    origin: "VietNam",
    category: "Cymbidium",
  },
  {
    id: 10,
    name: "Lan Long tu Lào",
    rating: 3,
    isSpecial: true,
    image:
      "https://cdn05.zipify.com/8ur9oa6m8oIdaAbcOla5t07fuhw=/0x0:2024x2024/fit-in/1080x0/174ed1dae2b942c3948d181c7a10aef4/large-faux-pink-orchid-arrangement-in-glass-vase-centerpiece-faux-floral-luxury-artificial-flowers-silk-vivian-rose_1024x1024-2x.jpeg",
    color: "pink",
    origin: "Taiwan",
    category: "Cymbidium",
  },
  {
    id: 11,
    name: "Chậu Lan Hồ Điệp Huy Hoàng",
    rating: 4,
    isSpecial: false,
    image:
      "https://hoaviet247.com/wp-content/uploads/2024/03/lan-ho-diep-cl008-gia-re.jpg",
    color: "yellow",
    origin: "Taiwan",
    category: "Cymbidium",
  },
  {
    id: 12,
    name: "Chậu Lan Hồ Điệp",
    rating: 5,
    isSpecial: true,
    image:
      "https://happyflower.vn/app/uploads/2020/05/Lan_3canhTrang_giayLua_XanhNgoc.jpg",
    color: "white",
    origin: "VietNam",
    category: "Cymbidium",
  },
  {
    id: 13,
    name: "Chậu Lan Hồ Điệp 5 Cành Sắc Tím",
    rating: 4,
    isSpecial: false,
    image:
      "https://hoaviet247.com/wp-content/uploads/2024/02/lan-ho-diep-cl007-sang-trong.jpg",
    color: "pink",
    origin: "Taiwan",
    category: "Cattleya",
  },
  {
    id: 14,
    name: "Chậu Lan Hồ Điệp Vàng Chúc Mừng",
    rating: 4.5,
    isSpecial: true,
    image:
      "http://bizweb.dktcdn.net/thumb/grande/100/261/741/products/chau-lan-ho-diep-vang-5-canh-hdv-0517.jpg?v=1527303959610",
    color: "yellow",
    origin: "VietNam",
    category: "Cymbidium",
  },
  {
    id: 15,
    name: "Chậu Lan Dịu Dàng",
    rating: 4,
    isSpecial: true,
    image:
      "https://tse4.mm.bing.net/th?id=OIP.PeTP1akILZuJaLo31PkOtAHaHa&pid=Api&P=0&h=220",
    color: "pink",
    origin: "Taiwan",
    category: "Cymbidium",
  },
  {
    id: 16,
    name: "Chậu Lan vũ nữ",
    rating: 5,
    isSpecial: true,
    image:
      "https://vuonmattroi.com/wp-content/uploads/2022/07/hoa-lan-vu-nu-so-huu-ve-dep-thanh-tao.jpg",
    color: "yellow",
    origin: "VietNam",
    category: "Dendrobium",
  },
];
